### ISSUE TITLE
Broken screenshot link

### ISSUE THREAD

**Issue by isaacbernat** [TasseDeCafe/netflix-sentence-adder#1]
Hi @TasseDeCafe . When I try to follow the image link in the readme I can't reach it. Seems broken. Could you add a screenshot or a new link? I wanted to reuse some of your instructions here https://github.com/isaacbernat/netflix-to-srt/pull/44 so feel free to add the image to the PR too if you want to become a contributor.

Thanks!

**Comment by TasseDeCafe** [comment]
Hi, I replied here: https://github.com/isaacbernat/netflix-to-srt/pull/44

**Comment by isaacbernat** [comment]
Thanks 🙏, then I'll close the issue
